package com.example.Springboot.CUSTOMER;

public enum Status {
    SUCCESSFULLY_REGISTERED,
    SUCCESSFULLY_LOGIN,
    SUCCESSFULLY_LOGOUT,
    SUCCESSFULLY_DELETED,
    USER_ALREADY_EXISTS,
    FAILURE
}

